/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type AnalysisRuleLinks struct {
	Self string `json:"Self,omitempty"`

	AnalysisRules string `json:"AnalysisRules,omitempty"`

	Analysis string `json:"Analysis,omitempty"`

	AnalysisTemplate string `json:"AnalysisTemplate,omitempty"`

	Parent string `json:"Parent,omitempty"`

	PlugIn string `json:"PlugIn,omitempty"`
}
