/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type AnalysisTemplateLinks struct {
	Self string `json:"Self,omitempty"`

	Database string `json:"Database,omitempty"`

	Categories string `json:"Categories,omitempty"`

	AnalysisRule string `json:"AnalysisRule,omitempty"`

	AnalysisRulePlugIn string `json:"AnalysisRulePlugIn,omitempty"`

	TimeRule string `json:"TimeRule,omitempty"`

	TimeRulePlugIn string `json:"TimeRulePlugIn,omitempty"`

	Target string `json:"Target,omitempty"`

	Security string `json:"Security,omitempty"`

	SecurityEntries string `json:"SecurityEntries,omitempty"`
}
