/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type AssetDatabaseLinks struct {
	Self string `json:"Self,omitempty"`

	Elements string `json:"Elements,omitempty"`

	ElementTemplates string `json:"ElementTemplates,omitempty"`

	EventFrames string `json:"EventFrames,omitempty"`

	AssetServer string `json:"AssetServer,omitempty"`

	ElementCategories string `json:"ElementCategories,omitempty"`

	AttributeCategories string `json:"AttributeCategories,omitempty"`

	TableCategories string `json:"TableCategories,omitempty"`

	AnalysisCategories string `json:"AnalysisCategories,omitempty"`

	AnalysisTemplates string `json:"AnalysisTemplates,omitempty"`

	EnumerationSets string `json:"EnumerationSets,omitempty"`

	Tables string `json:"Tables,omitempty"`

	Security string `json:"Security,omitempty"`

	SecurityEntries string `json:"SecurityEntries,omitempty"`
}
