/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type AssetServerLinks struct {
	Self string `json:"Self,omitempty"`

	Databases string `json:"Databases,omitempty"`

	NotificationContactTemplates string `json:"NotificationContactTemplates,omitempty"`

	SecurityIdentities string `json:"SecurityIdentities,omitempty"`

	SecurityMappings string `json:"SecurityMappings,omitempty"`

	UnitClasses string `json:"UnitClasses,omitempty"`

	AnalysisRulePlugIns string `json:"AnalysisRulePlugIns,omitempty"`

	TimeRulePlugIns string `json:"TimeRulePlugIns,omitempty"`

	Security string `json:"Security,omitempty"`

	SecurityEntries string `json:"SecurityEntries,omitempty"`
}
