/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type AttributeTemplateLinks struct {
	Self string `json:"Self,omitempty"`

	AttributeTemplates string `json:"AttributeTemplates,omitempty"`

	ElementTemplate string `json:"ElementTemplate,omitempty"`

	Parent string `json:"Parent,omitempty"`

	Categories string `json:"Categories,omitempty"`

	Trait string `json:"Trait,omitempty"`
}
