/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

import (
	"time"
)

type CacheInstance struct {
	Id string `json:"Id,omitempty"`

	LastRefreshTime time.Time `json:"LastRefreshTime,omitempty"`

	WillRefreshAfter time.Time `json:"WillRefreshAfter,omitempty"`

	ScheduledExpirationTime time.Time `json:"ScheduledExpirationTime,omitempty"`

	User string `json:"User,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
