/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type ChannelInstance struct {
	Id string `json:"Id,omitempty"`

	StartTime string `json:"StartTime,omitempty"`

	LastMessageSentTime string `json:"LastMessageSentTime,omitempty"`

	SentMessageCount int32 `json:"SentMessageCount,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
