/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type DataServerLicense struct {
	AmountLeft string `json:"AmountLeft,omitempty"`

	AmountUsed string `json:"AmountUsed,omitempty"`

	Name string `json:"Name,omitempty"`

	TotalAmount string `json:"TotalAmount,omitempty"`

	Links *DataServerLicenseLinks `json:"Links,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
