/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type ElementTemplateLinks struct {
	Self string `json:"Self,omitempty"`

	AnalysisTemplates string `json:"AnalysisTemplates,omitempty"`

	AttributeTemplates string `json:"AttributeTemplates,omitempty"`

	Database string `json:"Database,omitempty"`

	Categories string `json:"Categories,omitempty"`

	BaseTemplate string `json:"BaseTemplate,omitempty"`

	BaseTemplates string `json:"BaseTemplates,omitempty"`

	DerivedTemplates string `json:"DerivedTemplates,omitempty"`

	DefaultAttribute string `json:"DefaultAttribute,omitempty"`

	NotificationRuleTemplates string `json:"NotificationRuleTemplates,omitempty"`

	Security string `json:"Security,omitempty"`

	SecurityEntries string `json:"SecurityEntries,omitempty"`
}
