/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 * Contact: techsupport@osisoft.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package piwebapi

type ItemsItemAttribute struct {

	Items []ItemAttribute `json:"Items,omitempty"`

	Links *PaginationLinks `json:"Links,omitempty"`
}
