/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type ItemEventFrame struct {
	Identifier string `json:"Identifier,omitempty"`

	IdentifierType string `json:"IdentifierType,omitempty"`

	Object *EventFrame `json:"Object,omitempty"`

	Exception *Errors `json:"Exception,omitempty"`
}
