/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type LandingLinks struct {
	Self string `json:"Self,omitempty"`

	AssetServers string `json:"AssetServers,omitempty"`

	DataServers string `json:"DataServers,omitempty"`

	PIDirectory string `json:"PIDirectory,omitempty"`

	Search string `json:"Search,omitempty"`

	System string `json:"System,omitempty"`
}
