/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

import (
	"time"
)

type MediaMetadata struct {
	Author string `json:"Author,omitempty"`

	ChangeDate time.Time `json:"ChangeDate,omitempty"`

	Description string `json:"Description,omitempty"`

	Name string `json:"Name,omitempty"`

	Size float32 `json:"Size,omitempty"`

	Links *MediaMetadataLinks `json:"Links,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
