/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type Request struct {
	Method string `json:"Method,omitempty"`

	Resource string `json:"Resource,omitempty"`

	RequestTemplate *RequestTemplate `json:"RequestTemplate,omitempty"`

	Parameters []string `json:"Parameters,omitempty"`

	Headers map[string]string `json:"Headers,omitempty"`

	Content string `json:"Content,omitempty"`

	ParentIds []string `json:"ParentIds,omitempty"`
}
