/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type SearchByAttribute struct {
	SearchRoot string `json:"SearchRoot,omitempty"`

	ElementTemplate string `json:"ElementTemplate,omitempty"`

	Items []ValueQuery `json:"Items,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
