/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type SecurityRights struct {
	OwnerWebId string `json:"OwnerWebId,omitempty"`

	SecurityItem string `json:"SecurityItem,omitempty"`

	UserIdentity string `json:"UserIdentity,omitempty"`

	Links *SecurityRightsLinks `json:"Links,omitempty"`

	CanAnnotate bool `json:"CanAnnotate,omitempty"`

	CanDelete bool `json:"CanDelete,omitempty"`

	CanExecute bool `json:"CanExecute,omitempty"`

	CanRead bool `json:"CanRead,omitempty"`

	CanReadData bool `json:"CanReadData,omitempty"`

	CanSubscribe bool `json:"CanSubscribe,omitempty"`

	CanSubscribeOthers bool `json:"CanSubscribeOthers,omitempty"`

	CanWrite bool `json:"CanWrite,omitempty"`

	CanWriteData bool `json:"CanWriteData,omitempty"`

	HasAdmin bool `json:"HasAdmin,omitempty"`

	Rights []string `json:"Rights,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
