/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type SecurityIdentityLinks struct {
	Self string `json:"Self,omitempty"`

	AssetServer string `json:"AssetServer,omitempty"`

	SecurityMappings string `json:"SecurityMappings,omitempty"`

	Security string `json:"Security,omitempty"`

	SecurityEntries string `json:"SecurityEntries,omitempty"`
}
