/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type StreamValue struct {
	WebId string `json:"WebId,omitempty"`

	Name string `json:"Name,omitempty"`

	Path string `json:"Path,omitempty"`

	Value *TimedValue `json:"Value,omitempty"`

	Links *StreamValueLinks `json:"Links,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
