/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type SystemLanding struct {
	ProductTitle string `json:"ProductTitle,omitempty"`

	ProductVersion string `json:"ProductVersion,omitempty"`

	Links *SystemLandingLinks `json:"Links,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
