/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

import (
	"time"
)

type SystemStatus struct {
	UpTimeInMinutes float64 `json:"UpTimeInMinutes,omitempty"`

	State string `json:"State,omitempty"`

	CacheInstances int32 `json:"CacheInstances,omitempty"`

	ServerTime time.Time `json:"ServerTime,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
