/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type SystemLandingLinks struct {
	Self string `json:"Self,omitempty"`

	CacheInstances string `json:"CacheInstances,omitempty"`

	Configuration string `json:"Configuration,omitempty"`

	UserInfo string `json:"UserInfo,omitempty"`

	Versions string `json:"Versions,omitempty"`

	Status string `json:"Status,omitempty"`
}
