/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type TableData struct {
	Columns map[string]string `json:"Columns,omitempty"`

	Rows []map[string]interface{} `json:"Rows,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
