/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type UnitLinks struct {
	Self string `json:"Self,omitempty"`

	Class string `json:"Class,omitempty"`

	ReferenceUnit string `json:"ReferenceUnit,omitempty"`
}
