/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type UserInfo struct {
	IdentityType string `json:"IdentityType,omitempty"`

	Name string `json:"Name,omitempty"`

	IsAuthenticated bool `json:"IsAuthenticated,omitempty"`

	SID string `json:"SID,omitempty"`

	ImpersonationLevel string `json:"ImpersonationLevel,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
