/*
 * PI Web API 2018 Swagger Spec
 *
 * Swagger Spec file that describes PI Web API
 *
 * API version: 1.11.0.640
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gowebapi

type ValueQuery struct {
	AttributeName string `json:"AttributeName,omitempty"`

	AttributeUOM string `json:"AttributeUOM,omitempty"`

	AttributeValue *interface{} `json:"AttributeValue,omitempty"`

	SearchOperator string `json:"SearchOperator,omitempty"`

	WebException *WebException `json:"WebException,omitempty"`
}
